name: userbot_telegram
description: GENERAL FOSS userbot telegram simple by GENERAL FOSS dev.
version: 0.0.0
repository: https://github.com/generalfoss/userbot_telegram.git
homepage: https://github.com/generalfoss/userbot_telegram.git
issue_tracker: https://github.com/generalfoss/userbot_telegram.git

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  general_lib: ^0.0.27
  http: ^1.1.2
  mason_logger: ^0.2.12
  packagex: ^0.0.44
  path: ^1.9.0
  telegram_client: ^0.8.0
  translate_client: ^0.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  msix: ^3.16.7
  test: ^1.24.0

packagex:
  name: userbot_telegram
  dart_target: userbot_telegram
  flutter_target: main
  dart_name: userbot_telegram
  flutter_name: userbot_telegram
  is_without_platform_name: true
  flutter_commands:
    obfuscate: true
    split-debug-info: "0.0.5"
    build-name: "0.0.5"
    build-number: 40
    split-per-abi: true
    no-tree-shake-icons: false

  project_id: "azkadev.packagex"
  github_username: azkadev
  github_is_org: false
  

msix_config: 
  display_name: userbot_telegram
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.azka_userbot_telegram
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam
